[package]
name = "sudo"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
sudo-common = { path = "../lib/sudo-common" }
clap = { version = "4.0.32", features = ["derive"] }
